name: EKS Deployment Pipeline

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

jobs:
  # -----------------------------
  # Terraform Infra Deployment
  # -----------------------------
  terraform-infra:
    if: "!contains(github.event.head_commit.message, 'destroy')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init - Infra
        working-directory: eks-terraform/infra
        run: terraform init --reconfigure

      - name: Terraform Plan - Infra
        working-directory: eks-terraform/infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply - Infra
        working-directory: eks-terraform/infra
        run: terraform apply -auto-approve tfplan
        if: github.ref == 'refs/heads/dev'

      - name: Manual Approval - Infra (Main Branch)
        if: github.ref == 'refs/heads/main'
        run: echo "Awaiting manual approval for production infra deployment..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # -----------------------------
  # EKS Deployment
  # -----------------------------
  eks-deployment:
    if: "!contains(github.event.head_commit.message, 'destroy')"
    needs: terraform-infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init - EKS
        working-directory: terraform/eks/eks_module
        run: terraform init --reconfigure

      - name: Terraform Plan - EKS
        working-directory: terraform/eks/eks_module
        run: terraform plan -out=tfplan

      - name: Terraform Apply - EKS
        working-directory: terraform/eks/eks_module
        run: terraform apply -auto-approve tfplan
        if: github.ref == 'refs/heads/dev'

      - name: Manual Approval - EKS (Main Branch)
        if: github.ref == 'refs/heads/main'
        run: echo "Awaiting manual approval for production EKS deployment..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # -----------------------------
  # Destroy EKS First
  # -----------------------------
  destroy-eks:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'destroy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init - EKS
        working-directory: terraform/eks/eks_module
        run: terraform init --reconfigure

      - name: Terraform Destroy - EKS
        working-directory: terraform/eks/eks_module
        run: terraform destroy -auto-approve

  # -----------------------------
  # Destroy Infra After EKS
  # -----------------------------
  destroy-infra:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'destroy')
    needs: destroy-eks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init - Infra
        working-directory: eks-terraform
        run: terraform init --reconfigure

      - name: Terraform Destroy - Infra
        working-directory: eks-terraform
        run: terraform destroy -auto-approve





## below works perfectly

# name: EKS Deployment Pipeline

# on:
#   push:
#     branches:
#       - dev  # Dev branch
#       - main  # Production branch

# jobs:
#   eks-deployment:
#     # if: "!contains(github.event.head_commit.message, 'destroy')" #
#     runs-on: ubuntu-latest 
#     env:
#       AWS_REGION: "us-east-2"  # Set your desired AWS region
#       TF_ACTION: ${{ contains(github.event.head_commit.message, 'destroy') && 'destroy' || 'apply' }}  # Change to destroy if the commit message contains 'destroy'
#       TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}  # Environment variable for Terraform

#     steps:
#       - name: Checkout EKS deployment repo
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0  # Fetch full history
#           ref: ${{ github.ref }} # Checkout the branch that triggered the workflow

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.10.0

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Terraform Init
#         working-directory: eks-terraform
#         run: terraform init --reconfigure

#       - name: Terraform fmt
#         working-directory: eks-terraform
#         run: terraform fmt

#       - name: Terraform Validate
#         working-directory: eks-terraform
#         run: terraform validate

#       - name: Terraform Plan
#         working-directory: eks-terraform
#         run: terraform plan -out=tfplan

#       - name: Terraform Apply
#         working-directory: eks-terraform
#         run: terraform apply -auto-approve tfplan
#         if: github.ref == 'refs/heads/dev'  # Automatically apply for dev branch

#       - name: Manual Approval for Production
#         if: github.ref == 'refs/heads/main'  # Only for main branch
#         run: echo "Waiting for manual approval to proceed with production deployment..."
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#   eks-destroy:
#     if: contains(github.event.head_commit.message, 'destroy')  # Run only if 'destroy' is in commit message
#     runs-on: ubuntu-latest
#     # needs: eks-deployment  # Ensure this runs after deployment, but only if 'destroy' is in commit message
#     env:
#       AWS_REGION: "us-east-2"  # Set your desired AWS region
#       TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}  # Set environment variable for destroy

#     steps:
#       - name: Checkout EKS deployment repo
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           ref: ${{ github.ref }}

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3  
#         with:
#           terraform_version: 1.10.0

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Terraform Init
#         working-directory: eks-terraform
#         run: terraform init --reconfigure

#       - name: Terraform Validate
#         working-directory: eks-terraform
#         run: terraform validate

#       - name: Manual Approval for Destroy
#         if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'  # Allow manual approval on both branches
#         run: echo "Waiting for manual approval to proceed with destruction..."
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Terraform Destroy
#         working-directory: eks-terraform
#         run: terraform destroy -auto-approve
#         if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'  # Allow destroy on both branches
